### ISSUE TITLE
ocrd-kraken-ocr process call seems to be broken

### ISSUE THREAD

**Issue by j23d** [OCR-D/ocrd_kraken#30]
```bash
Traceback (most recent call last):
  File "/home/j23d/.local/share/virtualenvs/ocrd_butler-o_KhKE38/lib/python3.6/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/j23d/projects/ocrd_butler/ocrd_butler/celery_utils.py", line 21, in __call__
    return TaskBase.__call__(self, *args, **kwargs)
  File "/home/j23d/.local/share/virtualenvs/ocrd_butler-o_KhKE38/lib/python3.6/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/j23d/projects/ocrd_butler/ocrd_butler/execution/tasks.py", line 82, in create_task
    **kwargs)
  File "/home/j23d/.local/share/virtualenvs/ocrd_butler-o_KhKE38/lib/python3.6/site-packages/ocrd/processor/base.py", line 56, in run_processor
    processor.process()
  File "/home/j23d/.local/share/virtualenvs/ocrd_butler-o_KhKE38/lib/python3.6/site-packages/ocrd_kraken/ocr.py", line 44, in process
    content=bin_image_bytes.getvalue())
  File "/home/j23d/.local/share/virtualenvs/ocrd_butler-o_KhKE38/lib/python3.6/site-packages/ocrd/workspace.py", line 162, in add_file
    raise Exception("'content' was set but no 'local_filename'")
Exception: 'content' was set but no 'local_filename'
```

I suspect that the [call](https://github.com/OCR-D/ocrd_kraken/blob/cea90bd791384995275d6c76cea44cc247d4298e/ocrd_kraken/ocr.py#L18) is not up to date with the current version of [OCR-D core](https://github.com/OCR-D/core).

**Comment by bertsky** [comment]
> I suspect that the [call](https://github.com/OCR-D/ocrd_kraken/blob/cea90bd791384995275d6c76cea44cc247d4298e/ocrd_kraken/ocr.py#L18) is not up to date with the current version of [OCR-D core](https://github.com/OCR-D/core).

Absolutely. The requirement to specify `local_filename` for `add_file()` came somewhere around `0.15`. We now have `1.0.0` and `2.0.0a1`, which also requires using `workspace.image_from_page()` instead of `resolve_image_as_pil()`.

But specifically the `ocrd-kraken-ocr` is named wrong: all it does is `nlbin` binarization (and we already have a better version for that in `ocrd-cis-ocropy-binarize`). This processor should do the recognition (and perhaps request binarized images from the workspace).

**Comment by kba** [comment]
This has since been fixed, we rewrote the `-ocr` part.
